#!/bin/bash
# shellquizz
# Shellquizz main script.

# History
# 23/09/2014 - Paulo Ortolan - Script creation
# 15/10/2014 - Paulo Ortolan - Point to the new lib path
# 26/11/2015 - Paulo Ortolan - Renaming file without extension

source /usr/share/shellquizz/lib/shellquizz_lib.sh

main
